services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: pmu_backend
    env_file:
      - .env

    volumes:
      - .:/app
        
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "8000:8000"
    restart: on-failure

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    container_name: pmu_frontend
    depends_on:
      - backend
    environment:
      - API_URL=http://backend:8000
      - PYTHONUNBUFFERED=1
    
    volumes:
      - .:/app
      
    ports:
      - "8501:8501"