[theme]
base = "light"
primaryColor = "#ff4b4b"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f0f2f6"
textColor = "#31333F"
font = "sans serif"

[browser]
gatherUsageStats = false

[client]
# Change the visibility of items in the toolbar and options menu
# (top right of the app). The menu and toolbar contain viewer options
# (e.g. print, record screen, theme toggle) and developer options
# (e.g. deploy, rerun, clear cache).
#
# Allowed values:
# - "auto" : Show the developer options if the app is accessed through
# localhost or through Streamlit Community Cloud as a developer.
# Hide them otherwise.
# - "developer" : Show the developer options.
# - "viewer" : Hide the developer options, including the rerun, clear
# cache, and deploy button from the toolbar and menu.
# - "minimal" : Show only options set externally (e.g. through
# Streamlit Community Cloud) or through st.set_page_config.
# If there are no options left, hide the menu.
#
# Default: "auto"
toolbarMode = "auto"

[server]
headless = true

[secrets]
# List of locations where secrets are searched.
#
# An entry can be a path to a TOML file or directory path where
# Kubernetes style secrets are saved. Order is important, import is
# first to last, so secrets in later files will take precedence over
# earlier ones.
files = [ "F:\\git\\horse-racing-prediction\\.streamlit\\secrets.toml",]